
version: "3"
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    container_name: my_db
    expose:
    - "5432"
    ports:
      - "35432:5432"
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: user
      POSTGRES_DB: db_name
      DB_HOST: my_db

networks:
  webnet:
