
version: "3"
services:
  redis:
    image: redis
    networks:
      - webnet
  db:
    image: postgres
    container_name: my_database
    expose:
    - "5432"
    ports:
      - "35432:5432"
    networks:
      - webnet
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: user
      POSTGRES_DB: db_name
      DB_HOST: my_database
  web:
    image: my-node-app
    volumes:
     - .:/usr/src/app
     - /usr/src/app/config
     - /usr/src/app/models
    expose:
      - "5432"
    external_links:
      - my_database
    ports:
      - "3000:3000"
    networks:
      - webnet
    restart: always
    environment:
      DB_HOST: my_database
    depends_on:
      - db
      - redis
    command: npm run dev
networks:
  webnet:
